# Generated by Django 5.1.6 on 2025-02-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_teacher_year_teacher_end_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='agency',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
