# Generated by Django 5.1.6 on 2025-02-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_agency_teacher_teacher_teacher_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
