# Generated by Django 5.1.6 on 2025-02-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacher_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='title',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Department',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='FTGF',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='RegistrationNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='TeachingExperience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qalification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='serial_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacherName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
