# Generated by Django 5.1.6 on 2025-02-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_remove_teacher_agency_remove_teacher_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='dateOfBirth',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
