# Generated by Django 5.1.6 on 2025-02-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_alter_teacher_dateofbirth'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/Universityimages/')),
                ('alt', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='FTGF',
            new_name='ftgt',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='RegistrationNumber',
            new_name='qualification',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='TeachingExperience',
            new_name='registrationNumber',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='qalification',
            new_name='teachingExperience',
        ),
    ]
